# Generated by Django 4.2.13 on 2026-05-03 03:21

from django.db import migrations, models
from django.db.models import Q


def backfill_portal_reference_codes(apps, schema_editor):
    Booking = apps.get_model("customer", "Booking")
    qs = Booking.objects.filter(Q(reference_code__isnull=True) | Q(reference_code=""))
    for b in qs.iterator():
        from booking.utils import generate_portal_reference_code

        user = b.customer
        ref = generate_portal_reference_code(user, exclude_booking_pk=b.pk)
        Booking.objects.filter(pk=b.pk).update(reference_code=ref)


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_booking_date_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reference_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Human-readable code from username + role prefixes + digits (same scheme as catalog bookings).",
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(backfill_portal_reference_codes, migrations.RunPython.noop),
    ]
