# Generated by Django 4.2.13 on 2026-05-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='max_capacity',
            field=models.IntegerField(default=1),
        ),
    ]
