# Generated by Django 4.2.16 on 2026-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("one_to_one", "One-to-One"),
                    ("group", "Group"),
                    ("resource", "Resource-based"),
                ],
                default="one_to_one",
                max_length=20,
            ),
        ),
    ]
